server:
  port: 8080
  mode:debug

databae:
  mysql:
    host: localhost
    port: 3306
    username:root
    password:123456
    dbname:task_management
    charset:utf8mb4
    parse_time:true
    loc:Local
    max_idle_conns:10
    max_open_conns:100
    conn_max_lifetime:3600

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5